### ISSUE TITLE
delator -p Error Message

### ISSUE THREAD

**Issue by Rz-Rz** [netevert/delator#4]
I ran delator -p and I got this. I am using Ubuntu 20.04 on WSL2.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x955013]

goroutine 1 [running]:
main.storeKnownLogs()
        /home/afterburner/go/src/github.com/netevert/delator/delator.go:368 +0x173
main.setup()
        /home/afterburner/go/src/github.com/netevert/delator/delator.go:630 +0x485
main.main()
        /home/afterburner/go/src/github.com/netevert/delator/delator.go:664 +0x26

**Comment by Rz-Rz** [comment]
I had the wrong nameserver in my resolv.conf, I changed them and now it works fine.
